import type { SkillCatalog } from "@/lib/types";

export const DEFAULT_CATALOG: SkillCatalog = {
  skills: [
    "first aid",
    "triage",
    "nursing care",
    "medical support",
    "doctor",
    "emergency medicine",
    "wound care",
    "ambulance coordination",
    "mental health counseling",
    "psychosocial support",
    "logistics",
    "supply chain management",
    "warehouse operations",
    "crowd management",
    "food distribution",
    "meal planning",
    "shelter operations",
    "camp coordination",
    "community outreach",
    "case management",
    "teaching",
    "child safety",
    "translation",
    "sign language support",
    "data entry",
    "beneficiary registration",
    "fundraising support",
    "legal aid support",
    "disaster response",
    "search and rescue",
    "water sanitation",
    "hygiene promotion",
    "elderly care",
    "disability support",
    "animal rescue",
    "veterinary support",
    "driving",
    "heavy vehicle operations",
    "communications",
    "radio operations",
    "map reading",
    "gis mapping",
    "procurement",
    "volunteer coordination",
    "conflict mediation",
    "firefighting support",
  ],
  jobs: [
    "doctor",
    "nurse",
    "paramedic",
    "surgeon",
    "pharmacist",
    "physiotherapist",
    "psychologist",
    "teacher",
    "social worker",
    "community mobilizer",
    "child protection officer",
    "logistics coordinator",
    "supply chain specialist",
    "operations volunteer",
    "field coordinator",
    "incident commander",
    "search and rescue specialist",
    "ambulance driver",
    "driver",
    "data analyst",
    "it support",
    "public health officer",
    "veterinarian",
    "student",
    "counselor",
    "translator",
    "legal advisor",
    "retired professional",
  ],
  need_types: [
    "medical-camp",
    "food-distribution",
    "shelter",
    "relief-camp",
    "education",
    "community-support",
    "rescue-support",
    "search-rescue",
    "evacuation",
    "mental-health",
    "sanitation",
    "animal-rescue",
    "medical-transport",
  ],
  specialists: [
    "medical",
    "emergency-medicine",
    "trauma-care",
    "education",
    "disaster-management",
    "logistics",
    "communications",
    "it-support",
    "legal-aid",
    "veterinary",
    "counseling",
    "child-protection",
    "public-health",
  ],
  languages: [
    "english",
    "hindi",
    "bengali",
    "marathi",
    "tamil",
    "telugu",
    "kannada",
    "punjabi",
    "gujarati",
  ],
};
